Intro
Codernauti/GameBank-Report pull request #2
Opened 2018-04-08 10:02 UTC by Polpetta

Ho scritto un po' di intro. Sinceramente non aggiungerei niente, mi pare spieghi il problema e spieghi anche il perché dell'uso del bluetooth (forse andrebbe messa nella descrizione dell'app, ma penso che anche qui non ci stia male)

2018-04-15 19:57 UTC, EduBic requested changes

2018-04-15 19:57 UTC, EduBic commented on res/sections/02-Introduction.tex
> +~\cite{arango17} like, for example, Nintendo Labo.
Il pervasive game non mi sembra un concetto nato recentemente.

"Recently, a new  concept of [...] Nintendo Labo."

Lo sostituirei con:

> Recently a new concept of gaming, called pervasive gaming, is developing. This concept merges the opportunities of the digital world and the physical world. The most famous example of this is the mobile game Pokemon Go, published by Nintendo. Nintendo is continuing to develop this concept with the Nintendo Labo project: a physical extension for Nintendo Switch.

2018-04-15 19:57 UTC, EduBic commented on res/sections/02-Introduction.tex
> +games. This particular disposition makes an already established technology in
disposition -> scenario

2018-04-15 19:57 UTC, EduBic commented on res/sections/02-Introduction.tex
> +the market, Bluetooth, an optimal solution to implement these applications. In
these application -> Quali? Ci sono due argomenti che si intrecciano troppo e fanno perdere il filo logico del discorso

2018-04-16 07:22 UTC, Polpetta commented on res/sections/02-Introduction.tex
> +the market, Bluetooth, an optimal solution to implement these applications. In
È ovvio che si rivolga ai pervasive games, di quali altre tipologie di applicazione si parla nel paper? :thinking: Comunque vedo di cambiarlo

2018-04-16 09:22 UTC, EduBic commented on res/sections/02-Introduction.tex
> +making our application less naive for the avarage user. Secondly, Bluetooth can
avarage - >average

2018-04-16 09:24 UTC, EduBic requested changes

2018-04-16 09:24 UTC, EduBic commented on res/sections/02-Introduction.tex
> +WiFi-Direct, for example.\\
Non sarebbe da citare la fonte?

2018-04-16 11:44 UTC, Polpetta commented on res/sections/02-Introduction.tex
> +WiFi-Direct, for example.\\
Controllando qui pare non sia vero, quindi rimuovo quell'affermazione
https://ieeexplore.ieee.org/document/6549288/#full-text-section

2018-04-18 08:03 UTC, EduBic approved these changes

2018-04-18 08:04 UTC, merged