Future works
Codernauti/GameBank-Report pull request #4
Opened 2018-04-13 08:12 UTC by Polpetta

Purtroppo sta parte non è lunga in quanto non abbiamo molti future works da fare :disappointed:

2018-04-18 08:23 UTC, EduBic requested changes

2018-04-18 08:23 UTC, EduBic commented on res/sections/80-FutureWorks.tex
> +by MAC address o by username) as a new master and reinstantiate the match. This
o -> or

2018-04-18 08:23 UTC, EduBic commented on res/sections/80-FutureWorks.tex
> +require the user intervention, making the transition not seamless.
By the way, this feature is not trivial to achieve since Bluetooth API in Android requires the user intervention, making the transition not seamless.

2018-04-18 08:23 UTC, EduBic commented on res/sections/80-FutureWorks.tex
> +the hot-join feature, allowing new players to join an already started match.
a match already started? (Non sono sicuro)

2018-04-18 08:23 UTC, EduBic commented on res/sections/80-FutureWorks.tex
> +iscoverability}}.
Io qui proporrei una soluzione: 

A reasonable solution could be to give to host user the possibility to make discoverable his device.

2018-04-18 08:23 UTC, EduBic commented on res/sections/80-FutureWorks.tex
> +how much money a player has.
Io aggiungerei: This feature brings the application to be more general purpose making the application a game manager of the score of the players. Furthermore this extends the opportunities of user to use GameBank in different scenarios, also context not foreseen by ourself.

2018-04-23 07:13 UTC, Polpetta commented on res/sections/80-FutureWorks.tex
> +the hot-join feature, allowing new players to join an already started match.
Su internet dicono la prima :grin:

2018-04-23 07:17 UTC, Polpetta commented on res/sections/80-FutureWorks.tex
> +iscoverability}}.
` to make discoverable his device.` -> ` to make his device discoverable.`

2018-04-23 08:53 UTC, EduBic approved these changes

2018-04-23 08:53 UTC, merged